# Get the CELEX link using instructions here:
# https://eur-lex.europa.eu/content/help/data-reuse/linking.html
# https://eur-lex.europa.eu/content/help/eurlex-content/celex-number.html
#
# CELEX ids are only derivable from the regulation id for ordinary secondary
# legislation (EUR-Lex sector 3). International-agreement documents -
# Association Council / Joint Committee decisions, agreements and dumping
# notices - are published in sector 2 or the OJ C series, where the CELEX id
# is built from the OJ publication date and cannot be derived from the
# regulation id. For those we link by Official Journal citation instead,
# which EUR-Lex resolves to the right document (this is what DDS2-TARIC does).
module MeasureService
  class CouncilRegulationUrlGenerator
    EUR_LEX_BASE = 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri='.freeze

    # Only the L (Legislation) and C (Information and Notices) series carry
    # the documents we link; anything else falls back to the CELEX formula.
    OJ_NUMBER_PATTERN = /\A([LC])\s*(\d+)\z/

    # The EU moved to act-by-act OJ publication on 1 October 2023; from then
    # on OJ issues are no longer numbered and page-based citations do not
    # resolve. Post-change documents are numbered sequentially per year, which
    # the regulation id encodes, so the CELEX formula works for them.
    OJ_CITATION_CUTOFF = Date.new(2023, 10, 1)

    # Citations verified to resolve on EUR-Lex, and citations known to be
    # missing from it. Both lists are generated by the audit harness in
    # script/oj_citation_audit - re-run it to verify newly referenced
    # documents (see its README).
    OJ_CITATION_VERIFIED = File.readlines(
      File.expand_path('../../../lib/data/eur_lex_verified_oj_citations.txt', __dir__),
    ).filter_map { |line| line.strip.presence unless line.start_with?('#') }.to_set.freeze

    OJ_CITATION_DEAD = File.readlines(
      File.expand_path('../../../lib/data/eur_lex_dead_oj_citations.txt', __dir__),
    ).filter_map { |line| line.strip.presence unless line.start_with?('#') }.to_set.freeze

    attr_reader :target_regulation

    def initialize(target_regulation)
      @target_regulation = target_regulation
    end

    def generate
      return celex_url if council_regulation?

      oj_reference_url || celex_url
    end

  private

    def regulation_code
      @regulation_code ||= target_regulation.regulation_id
    end

    def council_regulation?
      regulation_code.start_with?('R')
    end

    def celex_url
      year = regulation_code[1..2]

      # When we get to 2071 assume that we don't care about the 1900's
      # or the EU has a better way to search
      full_year = if year.to_i > 70
                    "19#{year}"
                  else
                    "20#{year}"
                  end

      code = "3#{full_year}#{regulation_code.first}#{regulation_code[3..6]}"
      "#{EUR_LEX_BASE}CELEX%3A#{code}"
    end

    def oj_reference_url
      return nil unless citation_permitted?

      series, number = parse_oj_number
      return nil unless series

      page = target_regulation.try(:officialjournal_page).to_i
      return nil unless page.positive?

      published = target_regulation.try(:published_date)
      return nil unless published && published.to_date < OJ_CITATION_CUTOFF

      citation = sprintf('OJ.%<series>s_.%<year>d.%<number>03d.01.%<page>04d.01.ENG',
                         series:, year: published.year, number:, page:)
      "#{EUR_LEX_BASE}uriserv%3A#{citation}"
    end

    # Decisions (D-prefixed ids) can be ordinary sector-3 acts whose CELEX
    # formula link works, so an unverified citation could replace a working
    # link - they switch only once the audit has verified them. No other
    # non-R class has a working formula link to lose ("I" is not a CELEX
    # document type; agreements and joint-committee decisions live in
    # sector 2), so those default to the citation, minus the known-dead few.
    def citation_permitted?
      if regulation_code.start_with?('D')
        OJ_CITATION_VERIFIED.include?(regulation_code)
      else
        OJ_CITATION_DEAD.exclude?(regulation_code)
      end
    end

    def parse_oj_number
      match = OJ_NUMBER_PATTERN.match(target_regulation.try(:officialjournal_number).to_s.strip)
      return nil unless match

      [match[1], match[2].to_i]
    end
  end
end
