require 'csv'

# Get the CELEX link using instructions here:
# https://eur-lex.europa.eu/content/help/data-reuse/linking.html
# https://eur-lex.europa.eu/content/help/eurlex-content/celex-number.html
#
# The CELEX formula only resolves for acts EUR-Lex files in sector 3. Legal
# bases whose formula link is dead are listed in LINKS_FILE with the OJ
# citation a browser audit verified, or a blank citation when nothing
# resolves. Generated by trade-tariff-tools/scripts/eur-lex-legal-base-audit.
# One file serves UK and XI: the audit merges both services by regulation id
# and drops any citation the two disagree on.
module MeasureService
  class CouncilRegulationUrlGenerator
    LINKS_FILE = Rails.root.join('db/eur_lex_legal_base_links.csv').freeze
    OJ_CITATION_URL = 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=uriserv%3A'.freeze

    # Regulation id => OJ citation URL, or nil for no link
    LINKS = CSV.read(LINKS_FILE, headers: true).to_h { |row|
      citation = row['oj_citation']
      [row['regulation_id'], citation && "#{OJ_CITATION_URL}#{citation}".freeze]
    }.freeze

    # TARIC id types whose CELEX formula link never resolves (0 of 620 in the 2026-09 audit)
    NO_CELEX_TYPES = %w[A C I J].freeze

    attr_accessor :target_regulation

    def initialize(target_regulation)
      @target_regulation = target_regulation
    end

    def generate
      regulation_code = target_regulation.regulation_id

      return LINKS[regulation_code] if LINKS.key?(regulation_code)
      return if NO_CELEX_TYPES.include?(regulation_code.first) && !uk_national?

      year = regulation_code[1..2]

      # When we get to 2071 assume that we don't care about the 1900's
      # or the EU has a better way to search
      full_year = if year.to_i > 70
                    "19#{year}"
                  else
                    "20#{year}"
                  end

      code = "3#{full_year}#{regulation_code.first}#{regulation_code[3..6]}"
      "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A#{code}"
    end

  private

    # Same OJ number/page test as MeasureLegalActPresenter#uk?, but without its
    # TradeTariffBackend.uk? check: UK national regulations are out of scope and
    # keep their CELEX link on both services
    def uk_national?
      target_regulation.try(:officialjournal_number) == '1' &&
        target_regulation.try(:officialjournal_page) == 1
    end
  end
end
