version: 2
updates:

  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
    labels:
      - "needs-deployment"

  - package-ecosystem: "github-actions"
    directory: /
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
