# Add "needs-deployment" label to pull requests that should be deployed
# test: labeler/deploy-to-development race condition check
needs-deployment:
  - changed-files:
    - any-glob-to-any-file:
      - "db/**"
      - "Dockerfile"
      - "terraform/**"
      - "app/services/search_analytics/**"
      - "app/workers/search_analytics_snapshot_worker.rb"
      - "lib/tasks/search_analytics.rake"
      - ".github/labeler.yml"
      - ".github/workflows/deploy-to-development.yml"
