inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1.2
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'bin/**'
    - 'db/migrate/*'
    - 'db/data_migrations/*'
    - 'tmp/**/*'
    - 'config/puma.rb'

Layout/LineLength:
  Max: 120

Layout/AccessModifierIndentation:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - for

RSpec/ExampleLength:
  Enabled: false

RSpec/FilePath:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Rails/ActiveRecordAliases:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false # doesn't recognise

Rails/FindBy:
  Enabled: false # We use sequel not active record

Rails/SaveBang:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Style/Documentation:
  Enabled: false
  EnforcedStyle: never

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never

Style/GuardClause:
  MinBodyLength: 2

Style/OptionalBooleanParameter:
  Exclude:
    - 'app/workers/**/*.rb' # Sidekiq doesn't support kwargs syntax for jobs

Style/StringLiterals:
  EnforcedStyle: single_quotes
