inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml

plugins:
  - rubocop-rspec
  - rubocop-performance


AllCops:
  Exclude:
    - "db/schema.rb"
    - "vendor/**/*"
    - "bin/**"
    - "db/migrate/*"
    - "db/data_migrations/*"
    - "tmp/**/*"
    - "config/puma.rb"

RSpec:
  Language:
    Examples:
      Regular:
        - it_with_refresh_materialized_view

Layout/LineLength:
  Max: 120

Layout/AccessModifierIndentation:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: true
  Exclude:
    - spec/presenters/**/*
    - spec/serializers/**/*
    - spec/requests/**/*

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - for

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/ExampleLength:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

Rails/FilePath:
  Enabled: false

Rails/FindEach:
  Enabled: false

Rails/ActiveRecordAliases:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false # doesn't recognise

Rails/FindBy:
  Enabled: false # We use sequel not active record

Rails/SaveBang:
  Enabled: false

Rails/UniqueValidationWithoutIndex:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  MinBodyLength: 2

Style/OptionalBooleanParameter:
  Exclude:
    - "app/workers/**/*.rb" # Sidekiq doesn't support kwargs syntax for jobs

Style/StringLiterals:
  EnforcedStyle: single_quotes

RSpec/MessageChain:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false
