Sequel.migration do
  filename = '2023-02-15_duplicate_measure_type_fix.zip'.freeze

  # IMPORTANT! Data migrations up block should be idempotent (reruns of up should produce the same effect)
  # they may get re-run as part of data rollbacks but the rollback (down) function of the data migration will not get invoked
  up do
    if Measure.where(filename:).none? && TradeTariffBackend.uk?
      FootnoteAssociationMeasure.unrestrict_primary_key
      MeasureCondition.unrestrict_primary_key
      MeasureExcludedGeographicalArea.unrestrict_primary_key
      Measure.unrestrict_primary_key

      # Delete the duplicate measure components that were not deleted with the CDS correction file
      # These would surface on the wrong measure if we left them intact.
      MeasureComponent.where(measure_sid: 20_200_327, filename: 'tariff_dailyExtract_v1_20230214T235959.gzip').destroy

      # Add back in the deleted measures and their asscoiated resources
      FootnoteAssociationMeasure.new({ 'national' => false, 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_325, 'footnote_type_id' => 'CD', 'footnote_id' => '624', 'filename' => filename }).save
      FootnoteAssociationMeasure.new({ 'national' => false, 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_325, 'footnote_type_id' => 'CD', 'footnote_id' => '686', 'filename' => filename }).save
      FootnoteAssociationMeasure.new({ 'national' => false, 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_325, 'footnote_type_id' => 'CD', 'footnote_id' => '737', 'filename' => filename }).save
      FootnoteAssociationMeasure.new({ 'national' => false, 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_326, 'footnote_type_id' => 'CD', 'footnote_id' => '624', 'filename' => filename }).save
      FootnoteAssociationMeasure.new({ 'national' => false, 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_326, 'footnote_type_id' => 'CD', 'footnote_id' => '686', 'filename' => filename }).save
      FootnoteAssociationMeasure.new({ 'national' => false, 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_326, 'footnote_type_id' => 'CD', 'footnote_id' => '737', 'filename' => filename }).save
      FootnoteAssociationMeasure.new({ 'national' => false, 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_327, 'footnote_type_id' => 'CD', 'footnote_id' => '624', 'filename' => filename }).save
      FootnoteAssociationMeasure.new({ 'national' => false, 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_327, 'footnote_type_id' => 'CD', 'footnote_id' => '686', 'filename' => filename }).save
      FootnoteAssociationMeasure.new({ 'national' => false, 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_327, 'footnote_type_id' => 'CD', 'footnote_id' => '737', 'filename' => filename }).save
      FootnoteAssociationMeasure.new({ 'national' => false, 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_328, 'footnote_type_id' => 'CD', 'footnote_id' => '624', 'filename' => filename }).save
      FootnoteAssociationMeasure.new({ 'national' => false, 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_328, 'footnote_type_id' => 'CD', 'footnote_id' => '686', 'filename' => filename }).save
      FootnoteAssociationMeasure.new({ 'national' => false, 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_328, 'footnote_type_id' => 'CD', 'footnote_id' => '737', 'filename' => filename }).save
      FootnoteAssociationMeasure.new({ 'national' => false, 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_329, 'footnote_type_id' => 'CD', 'footnote_id' => '624', 'filename' => filename }).save
      FootnoteAssociationMeasure.new({ 'national' => false, 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_329, 'footnote_type_id' => 'CD', 'footnote_id' => '686', 'filename' => filename }).save
      FootnoteAssociationMeasure.new({ 'national' => false, 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_329, 'footnote_type_id' => 'CD', 'footnote_id' => '737', 'filename' => filename }).save
      FootnoteAssociationMeasure.new({ 'national' => false, 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_330, 'footnote_type_id' => 'CD', 'footnote_id' => '624', 'filename' => filename }).save
      FootnoteAssociationMeasure.new({ 'national' => false, 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_330, 'footnote_type_id' => 'CD', 'footnote_id' => '686', 'filename' => filename }).save
      FootnoteAssociationMeasure.new({ 'national' => false, 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_330, 'footnote_type_id' => 'CD', 'footnote_id' => '737', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_325, 'measure_condition_sid' => 20_244_257, 'condition_code' => 'B', 'component_sequence_number' => 1, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'N', 'certificate_code' => '853', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_325, 'measure_condition_sid' => 20_244_258, 'condition_code' => 'B', 'component_sequence_number' => 2, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'Y', 'certificate_code' => '058', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_325, 'measure_condition_sid' => 20_244_259, 'condition_code' => 'B', 'component_sequence_number' => 3, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'C', 'certificate_code' => '084', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_325, 'measure_condition_sid' => 20_244_260, 'condition_code' => 'B', 'component_sequence_number' => 4, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '09', 'certificate_type_code' => nil, 'certificate_code' => nil, 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_325, 'measure_condition_sid' => 20_244_261, 'condition_code' => 'E', 'component_sequence_number' => 5, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'N', 'certificate_code' => '853', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_325, 'measure_condition_sid' => 20_244_262, 'condition_code' => 'E', 'component_sequence_number' => 6, 'condition_duty_amount' => 2.0, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => nil, 'certificate_code' => nil, 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_325, 'measure_condition_sid' => 20_244_263, 'condition_code' => 'E', 'component_sequence_number' => 7, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'C', 'certificate_code' => '084', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_325, 'measure_condition_sid' => 20_244_264, 'condition_code' => 'E', 'component_sequence_number' => 8, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '09', 'certificate_type_code' => nil, 'certificate_code' => nil, 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_326, 'measure_condition_sid' => 20_244_265, 'condition_code' => 'B', 'component_sequence_number' => 1, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'N', 'certificate_code' => '853', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_326, 'measure_condition_sid' => 20_244_266, 'condition_code' => 'B', 'component_sequence_number' => 2, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'Y', 'certificate_code' => '058', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_326, 'measure_condition_sid' => 20_244_267, 'condition_code' => 'B', 'component_sequence_number' => 3, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'C', 'certificate_code' => '084', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_326, 'measure_condition_sid' => 20_244_268, 'condition_code' => 'B', 'component_sequence_number' => 4, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '09', 'certificate_type_code' => nil, 'certificate_code' => nil, 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_326, 'measure_condition_sid' => 20_244_269, 'condition_code' => 'E', 'component_sequence_number' => 5, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'N', 'certificate_code' => '853', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_326, 'measure_condition_sid' => 20_244_270, 'condition_code' => 'E', 'component_sequence_number' => 6, 'condition_duty_amount' => 2.0, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => nil, 'certificate_code' => nil, 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_326, 'measure_condition_sid' => 20_244_271, 'condition_code' => 'E', 'component_sequence_number' => 7, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'C', 'certificate_code' => '084', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_326, 'measure_condition_sid' => 20_244_272, 'condition_code' => 'E', 'component_sequence_number' => 8, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '09', 'certificate_type_code' => nil, 'certificate_code' => nil, 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_327, 'measure_condition_sid' => 20_244_273, 'condition_code' => 'B', 'component_sequence_number' => 1, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'N', 'certificate_code' => '853', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_327, 'measure_condition_sid' => 20_244_274, 'condition_code' => 'B', 'component_sequence_number' => 2, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'Y', 'certificate_code' => '058', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_327, 'measure_condition_sid' => 20_244_275, 'condition_code' => 'B', 'component_sequence_number' => 3, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'C', 'certificate_code' => '084', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_327, 'measure_condition_sid' => 20_244_276, 'condition_code' => 'B', 'component_sequence_number' => 4, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '09', 'certificate_type_code' => nil, 'certificate_code' => nil, 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_327, 'measure_condition_sid' => 20_244_277, 'condition_code' => 'E', 'component_sequence_number' => 5, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'N', 'certificate_code' => '853', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_327, 'measure_condition_sid' => 20_244_278, 'condition_code' => 'E', 'component_sequence_number' => 6, 'condition_duty_amount' => 2.0, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => nil, 'certificate_code' => nil, 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_327, 'measure_condition_sid' => 20_244_279, 'condition_code' => 'E', 'component_sequence_number' => 7, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'C', 'certificate_code' => '084', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_327, 'measure_condition_sid' => 20_244_280, 'condition_code' => 'E', 'component_sequence_number' => 8, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '09', 'certificate_type_code' => nil, 'certificate_code' => nil, 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_328, 'measure_condition_sid' => 20_244_281, 'condition_code' => 'B', 'component_sequence_number' => 1, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'N', 'certificate_code' => '853', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_328, 'measure_condition_sid' => 20_244_282, 'condition_code' => 'B', 'component_sequence_number' => 2, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'Y', 'certificate_code' => '058', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_328, 'measure_condition_sid' => 20_244_283, 'condition_code' => 'B', 'component_sequence_number' => 3, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'C', 'certificate_code' => '084', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_328, 'measure_condition_sid' => 20_244_284, 'condition_code' => 'B', 'component_sequence_number' => 4, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '09', 'certificate_type_code' => nil, 'certificate_code' => nil, 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_328, 'measure_condition_sid' => 20_244_285, 'condition_code' => 'E', 'component_sequence_number' => 5, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'N', 'certificate_code' => '853', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_328, 'measure_condition_sid' => 20_244_286, 'condition_code' => 'E', 'component_sequence_number' => 6, 'condition_duty_amount' => 2.0, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => nil, 'certificate_code' => nil, 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_328, 'measure_condition_sid' => 20_244_287, 'condition_code' => 'E', 'component_sequence_number' => 7, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'C', 'certificate_code' => '084', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_328, 'measure_condition_sid' => 20_244_288, 'condition_code' => 'E', 'component_sequence_number' => 8, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '09', 'certificate_type_code' => nil, 'certificate_code' => nil, 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_329, 'measure_condition_sid' => 20_244_289, 'condition_code' => 'B', 'component_sequence_number' => 1, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'N', 'certificate_code' => '853', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_329, 'measure_condition_sid' => 20_244_290, 'condition_code' => 'B', 'component_sequence_number' => 2, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'Y', 'certificate_code' => '058', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_329, 'measure_condition_sid' => 20_244_291, 'condition_code' => 'B', 'component_sequence_number' => 3, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'C', 'certificate_code' => '084', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_329, 'measure_condition_sid' => 20_244_292, 'condition_code' => 'B', 'component_sequence_number' => 4, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '09', 'certificate_type_code' => nil, 'certificate_code' => nil, 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_329, 'measure_condition_sid' => 20_244_293, 'condition_code' => 'E', 'component_sequence_number' => 5, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'N', 'certificate_code' => '853', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_329, 'measure_condition_sid' => 20_244_294, 'condition_code' => 'E', 'component_sequence_number' => 6, 'condition_duty_amount' => 2.0, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => nil, 'certificate_code' => nil, 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_329, 'measure_condition_sid' => 20_244_295, 'condition_code' => 'E', 'component_sequence_number' => 7, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'C', 'certificate_code' => '084', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_329, 'measure_condition_sid' => 20_244_296, 'condition_code' => 'E', 'component_sequence_number' => 8, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '09', 'certificate_type_code' => nil, 'certificate_code' => nil, 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_330, 'measure_condition_sid' => 20_244_297, 'condition_code' => 'B', 'component_sequence_number' => 1, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'N', 'certificate_code' => '853', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_330, 'measure_condition_sid' => 20_244_298, 'condition_code' => 'B', 'component_sequence_number' => 2, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'Y', 'certificate_code' => '058', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_330, 'measure_condition_sid' => 20_244_299, 'condition_code' => 'B', 'component_sequence_number' => 3, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'C', 'certificate_code' => '084', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_330, 'measure_condition_sid' => 20_244_300, 'condition_code' => 'B', 'component_sequence_number' => 4, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '09', 'certificate_type_code' => nil, 'certificate_code' => nil, 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_330, 'measure_condition_sid' => 20_244_301, 'condition_code' => 'E', 'component_sequence_number' => 5, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'N', 'certificate_code' => '853', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_330, 'measure_condition_sid' => 20_244_302, 'condition_code' => 'E', 'component_sequence_number' => 6, 'condition_duty_amount' => 2.0, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => nil, 'certificate_code' => nil, 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_330, 'measure_condition_sid' => 20_244_303, 'condition_code' => 'E', 'component_sequence_number' => 7, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '29', 'certificate_type_code' => 'C', 'certificate_code' => '084', 'filename' => filename }).save
      MeasureCondition.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_330, 'measure_condition_sid' => 20_244_304, 'condition_code' => 'E', 'component_sequence_number' => 8, 'condition_duty_amount' => nil, 'condition_monetary_unit_code' => nil, 'condition_measurement_unit_code' => nil, 'condition_measurement_unit_qualifier_code' => nil, 'action_code' => '09', 'certificate_type_code' => nil, 'certificate_code' => nil, 'filename' => filename }).save
      MeasureExcludedGeographicalArea.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_325, 'excluded_geographical_area' => 'IE', 'geographical_area_sid' => 397, 'filename' => filename }).save
      MeasureExcludedGeographicalArea.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_326, 'excluded_geographical_area' => 'IE', 'geographical_area_sid' => 397, 'filename' => filename }).save
      MeasureExcludedGeographicalArea.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_327, 'excluded_geographical_area' => 'IE', 'geographical_area_sid' => 397, 'filename' => filename }).save
      MeasureExcludedGeographicalArea.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_328, 'excluded_geographical_area' => 'IE', 'geographical_area_sid' => 397, 'filename' => filename }).save
      MeasureExcludedGeographicalArea.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_329, 'excluded_geographical_area' => 'IE', 'geographical_area_sid' => 397, 'filename' => filename }).save
      MeasureExcludedGeographicalArea.new({ 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_330, 'excluded_geographical_area' => 'IE', 'geographical_area_sid' => 397, 'filename' => filename }).save
      Measure.new({ 'validity_start_date' => '2023-02-01T00:00:00.000Z', 'validity_end_date' => nil, 'national' => false, 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_325, 'measure_type_id' => '410', 'geographical_area_id' => '1011', 'geographical_area_sid' => 400, 'goods_nomenclature_item_id' => '2309101300', 'goods_nomenclature_sid' => 35_193, 'measure_generating_regulation_role' => 1, 'measure_generating_regulation_id' => 'A1907820', 'justification_regulation_role' => nil, 'justification_regulation_id' => nil, 'stopped_flag' => false, 'ordernumber' => nil, 'additional_code_type_id' => nil, 'additional_code_id' => nil, 'additional_code_sid' => nil, 'reduction_indicator' => nil, 'export_refund_nomenclature_sid' => nil, 'filename' => filename }).save
      Measure.new({ 'validity_start_date' => '2023-02-01T00:00:00.000Z', 'validity_end_date' => nil, 'national' => false, 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_326, 'measure_type_id' => '410', 'geographical_area_id' => '1011', 'geographical_area_sid' => 400, 'goods_nomenclature_item_id' => '2309101500', 'goods_nomenclature_sid' => 35_194, 'measure_generating_regulation_role' => 1, 'measure_generating_regulation_id' => 'A1907820', 'justification_regulation_role' => nil, 'justification_regulation_id' => nil, 'stopped_flag' => false, 'ordernumber' => nil, 'additional_code_type_id' => nil, 'additional_code_id' => nil, 'additional_code_sid' => nil, 'reduction_indicator' => nil, 'export_refund_nomenclature_sid' => nil, 'filename' => filename }).save
      Measure.new({ 'validity_start_date' => '2023-02-01T00:00:00.000Z', 'validity_end_date' => nil, 'national' => false, 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_327, 'measure_type_id' => '410', 'geographical_area_id' => '1011', 'geographical_area_sid' => 400, 'goods_nomenclature_item_id' => '2309101900', 'goods_nomenclature_sid' => 35_195, 'measure_generating_regulation_role' => 1, 'measure_generating_regulation_id' => 'A1907820', 'justification_regulation_role' => nil, 'justification_regulation_id' => nil, 'stopped_flag' => false, 'ordernumber' => nil, 'additional_code_type_id' => nil, 'additional_code_id' => nil, 'additional_code_sid' => nil, 'reduction_indicator' => nil, 'export_refund_nomenclature_sid' => nil, 'filename' => filename }).save
      Measure.new({ 'validity_start_date' => '2023-02-01T00:00:00.000Z', 'validity_end_date' => nil, 'national' => false, 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_328, 'measure_type_id' => '410', 'geographical_area_id' => '1011', 'geographical_area_sid' => 400, 'goods_nomenclature_item_id' => '2309103300', 'goods_nomenclature_sid' => 35_198, 'measure_generating_regulation_role' => 1, 'measure_generating_regulation_id' => 'A1907820', 'justification_regulation_role' => nil, 'justification_regulation_id' => nil, 'stopped_flag' => false, 'ordernumber' => nil, 'additional_code_type_id' => nil, 'additional_code_id' => nil, 'additional_code_sid' => nil, 'reduction_indicator' => nil, 'export_refund_nomenclature_sid' => nil, 'filename' => filename }).save
      Measure.new({ 'validity_start_date' => '2023-02-01T00:00:00.000Z', 'validity_end_date' => nil, 'national' => false, 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_329, 'measure_type_id' => '410', 'geographical_area_id' => '1011', 'geographical_area_sid' => 400, 'goods_nomenclature_item_id' => '2309103900', 'goods_nomenclature_sid' => 35_199, 'measure_generating_regulation_role' => 1, 'measure_generating_regulation_id' => 'A1907820', 'justification_regulation_role' => nil, 'justification_regulation_id' => nil, 'stopped_flag' => false, 'ordernumber' => nil, 'additional_code_type_id' => nil, 'additional_code_id' => nil, 'additional_code_sid' => nil, 'reduction_indicator' => nil, 'export_refund_nomenclature_sid' => nil, 'filename' => filename }).save
      Measure.new({ 'validity_start_date' => '2023-02-01T00:00:00.000Z', 'validity_end_date' => nil, 'national' => false, 'operation' => 'C', 'operation_date' => '2023-01-30', 'measure_sid' => 20_200_330, 'measure_type_id' => '410', 'geographical_area_id' => '1011', 'geographical_area_sid' => 400, 'goods_nomenclature_item_id' => '2309105300', 'goods_nomenclature_sid' => 35_202, 'measure_generating_regulation_role' => 1, 'measure_generating_regulation_id' => 'A1907820', 'justification_regulation_role' => nil, 'justification_regulation_id' => nil, 'stopped_flag' => false, 'ordernumber' => nil, 'additional_code_type_id' => nil, 'additional_code_id' => nil, 'additional_code_sid' => nil, 'reduction_indicator' => nil, 'export_refund_nomenclature_sid' => nil, 'filename' => filename }).save

    end
  end

  down do
    if    TradeTariffBackend.uk?
      MeasureComponent.unrestrict_primary_key
      MeasureComponent.new({ 'measure_sid' => 20_200_327, 'duty_expression_id' => '01', 'duty_amount' => 5.2, 'monetary_unit_code' => nil, 'measurement_unit_code' => nil, 'measurement_unit_qualifier_code' => nil, 'operation' => 'C', 'operation_date' => '2023-01-30', 'filename' => 'tariff_dailyExtract_v1_20230214T235959.gzip' }).save
      MeasureComponent.new({ 'measure_sid' => 20_200_327, 'duty_expression_id' => '04', 'duty_amount' => 8.0, 'monetary_unit_code' => 'GBP', 'measurement_unit_code' => 'DTN', 'measurement_unit_qualifier_code' => nil, 'operation' => 'C', 'operation_date' => '2023-01-30', 'filename' => 'tariff_dailyExtract_v1_20230214T235959.gzip' }).save

      FootnoteAssociationMeasure.where(filename:).destroy
      MeasureCondition.where(filename:).destroy
      MeasureExcludedGeographicalArea.where(filename:).destroy
      Measure.where(filename:).destroy
    end
  end
end
