name: ci

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main
  workflow_dispatch:

env:
  AWS_REGION: eu-west-2
  BUNDLE_JOBS: "3"
  BUNDLE_RETRY: "3"
  DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/tariff_test"
  ECR_URL: 382373577178.dkr.ecr.eu-west-2.amazonaws.com/tariff-backend-production
  ENVIRONMENT: development
  IAM_ROLE_ARN: arn:aws:iam::844815912454:role/GithubActions-ECS-Deployments-Role
  RAILS_ENV: test

permissions:
  contents: read
  id-token: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pre-commit-
      - uses: actions/setup-python@v5
        with:
          python-version: '3'
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.0
      - uses: trade-tariff/trade-tariff-tools/.github/actions/setup-tflint@main
      - uses: trade-tariff/trade-tariff-tools/.github/actions/setup-terraform-docs@main
      - uses: trade-tariff/trade-tariff-tools/.github/actions/setup-ssh@main
        with:
          ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}
      - run: cd terraform/ && terraform init -backend=false -reconfigure
      - run: pip install pre-commit
      - run: pre-commit run --all-files
      - run: bundle exec brakeman

  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tariff_test
        ports:
          - 5432:5432
      redis:
        image: redis:7
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4

      - uses: ankane/setup-opensearch@v1
        with:
          opensearch-version: 2

      - run: echo "127.0.0.1 host.docker.internal" | sudo tee -a /etc/hosts

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: bundle exec rails db:structure:load --trace

      - run: bundle exec rspec
