name: "Production Deployment"
on: [workflow_dispatch]
jobs:
  deploy_production:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        service: ["tariff-uk-backend-production", "tariff-xi-backend-production"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: "Deploy production"
        env:
          CF_APP_API_NAME: "${{ matrix.service }}"
          CF_APP_ADMIN: "tariff-admin-production"
          CF_APP_FRONTEND: "tariff-frontend-production"
          CF_ENDPOINT: "api.london.cloud.service.gov.uk"
          CF_ORG: ${{ secrets.CF_ORG }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          CF_SPACE: production
          CF_USER: ${{ secrets.CF_USER }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          curl -L -o cf.deb 'https://packages.cloudfoundry.org/stable?release=debian64&version=7.2.0&source=github-rel'
          sudo dpkg -i cf.deb
          cf -v
          cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
          cf install-plugin blue-green-deploy -r CF-Community -f
          cf install-plugin app-autoscaler-plugin -r CF-Community -f
          ./bin/deploy
  sentry_release:
    runs-on: ubuntu-latest
    needs: [deploy_production]
    steps:
      - uses: actions/checkout@v2
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: tariff-backend
        with:
          environment: production
