name: Deploy to development

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
      - unlabeled

concurrency:
  group: deploy-development
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    if: >
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.pull_request.labels.*.name, 'needs-deployment')
    uses: trade-tariff/trade-tariff-tools/.github/workflows/deploy-ecs.yml@main
    with:
      app-name: tariff-backend
      environment: development
      test-flavour: none
      migrate: true
    secrets:
      slack-webhook: ${{ secrets.SLACK_WEBHOOK }}
      ssh-key: ${{ secrets.PRIVATE_SSH_KEY }}

  start-services:
    if: >
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.pull_request.labels.*.name, 'needs-deployment')
    runs-on: ubuntu-latest
    steps:
      - uses: trade-tariff/trade-tariff-tools/.github/actions/start-services@main
        with:
          service-names: backend-uk backend-xi worker-uk worker-xi
          environment: development

  newrelic:
    if: >
      github.event_name == 'workflow_dispatch' ||
      contains(github.event.pull_request.labels.*.name, 'needs-deployment')
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v6
      - id: docker-tag
        run: echo "DOCKER_TAG=$(git rev-parse --short HEAD)" >> "$GITHUB_OUTPUT"
      - name: New Relic deployment marker for backend UK
        uses: newrelic/deployment-marker-action@v2.6.2
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          region: "EU"
          guid: ${{ secrets.NEW_RELIC_BACKEND_UK_GUID }}
          version: ${{ steps.docker-tag.outputs.DOCKER_TAG }}
          user: "${{ github.actor }}"
      - name: New Relic deployment marker for backend XI
        uses: newrelic/deployment-marker-action@v2.6.2
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          region: "EU"
          guid: ${{ secrets.NEW_RELIC_BACKEND_XI_GUID }}
          version: ${{ steps.docker-tag.outputs.DOCKER_TAG }}
          user: "${{ github.actor }}"
      - name: New Relic deployment marker for worker UK
        uses: newrelic/deployment-marker-action@v2.6.2
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          region: "EU"
          guid: ${{ secrets.NEW_RELIC_WORKER_UK_GUID }}
          version: ${{ steps.docker-tag.outputs.DOCKER_TAG }}
          user: "${{ github.actor }}"
      - name: New Relic deployment marker for worker XI
        uses: newrelic/deployment-marker-action@v2.6.2
        with:
          apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
          region: "EU"
          guid: ${{ secrets.NEW_RELIC_WORKER_XI_GUID }}
          version: ${{ steps.docker-tag.outputs.DOCKER_TAG }}
          user: "${{ github.actor }}"
