name: Release Notes

on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * 1,4"

jobs:
  release_notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Post release notes to slack
        run: bash bin/post_release_notes.sh
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_CHANNEL: "trade_tariff"
          SLACK_USERNAME: 'Release Bot'
