name: Run DB Replicate Job

on:
  workflow_dispatch:

jobs:
  run-job:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-2
      CLUSTER: trade-tariff-cluster-prod
      TASK_DEFINITION: worker-uk-job

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Run ECS task
        run: |
          aws ecs run-task \
            --cluster $CLUSTER \
            --launch-type FARGATE \
            --network-configuration "awsvpcConfiguration={subnets=[subnet-abc123],securityGroups=[sg-abc123],assignPublicIp=DISABLED}" \
            --task-definition $TASK_DEFINITION \
            --overrides '{
              "containerOverrides": [{
                "name": "worker-uk",
                "environment": [{
                  "name": "TAG",
                  "value": "${{ github.event.inputs.docker_tag }}"
                }]
              }]
            }'
