name: Stop Development Services

on:
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'

permissions:
  contents: read
  id-token: write

jobs:
  stop-services:
    runs-on: ubuntu-latest
    steps:
      - uses: trade-tariff/trade-tariff-tools/.github/actions/stop-services@main
        with:
          service-names: backend-uk backend-xi worker-uk worker-xi backend-job
          environment: development
